// client/src/pages/Login.jsx
import { createSignal } from 'solid-js';
import { login } from '../api';

const Login = (props) => {
  const [phone, setPhone] = createSignal('');
  const [loading, setLoading] = createSignal(false);
  const [error, setError] = createSignal('');

  const handleSubmit = async (e) => {
    e.preventDefault();
    setLoading(true);
    setError('');

    try {
      const result = await login(phone());
      if (result.error) {
        setError(result.error);
      } else {
        if (props.onLogin) {
          props.onLogin(result.user, result.hasDrawn, result.coupon);
        }
      }
    } catch (err) {
      setError('登录失败，请稍后重试');
    } finally {
      setLoading(false);
    }
  };

  return (
    <div class="login-container">
      <h2>手机号登录</h2>
      <form onSubmit={handleSubmit}>
        <div class="form-group">
          <label>请输入手机号</label>
          <input
            type="tel"
            value={phone()}
            onInput={(e) => setPhone(e.target.value)}
            placeholder="11位手机号码"
            maxLength={11}
            required
          />
        </div>
        {error() && <div class="status-message error">{error()}</div>}
        <button type="submit" class="btn btn-primary" disabled={loading()}>
          {loading() ? '登录中...' : '开始刮奖'}
        </button>
      </form>
    </div>
  );
};

export default Login;

// frontend/src/components/Login.tsx
import React, { useState } from 'react';

interface LoginProps {
  onLogin: (token: string, user: any) => void;
  onSwitchToRegister: () => void;
}

export function Login({ onLogin, onSwitchToRegister }: LoginProps) {
  const [email, setEmail] = useState('');
  const [phone, setPhone] = useState('');
  const [username, setUsername] = useState('');
  const [password, setPassword] = useState('');
  const [error, setError] = useState('');
  const [loading, setLoading] = useState(false);

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setError('');
    setLoading(true);

    try {
      const payload: any = { password };
      if (email) payload.email = email;
      if (phone) payload.phone = phone;
      if (username) payload.username = username;

      const response = await fetch('http://localhost:3950/api/auth/login', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(payload),
      });

      const data = await response.json();
      if (!response.ok) {
        throw new Error(data.error || 'Login failed');
      }

      onLogin(data.token, data.user);
    } catch (err: any) {
      setError(err.message);
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="auth-container">
      <div className="auth-card">
        <h2>登录 Web CLI</h2>
        {error && <div className="auth-error">{error}</div>}
        <form onSubmit={handleSubmit}>
          <div className="form-group">
            <label>邮箱</label>
            <input
              type="email"
              value={email}
              onChange={(e) => setEmail(e.target.value)}
              placeholder="输入邮箱"
            />
          </div>
          <div className="form-group">
            <label>或手机号</label>
            <input
              type="tel"
              value={phone}
              onChange={(e) => setPhone(e.target.value)}
              placeholder="输入手机号"
            />
          </div>
          <div className="form-group">
            <label>或用户名</label>
            <input
              type="text"
              value={username}
              onChange={(e) => setUsername(e.target.value)}
              placeholder="输入用户名"
            />
          </div>
          <div className="form-group">
            <label>密码</label>
            <input
              type="password"
              value={password}
              onChange={(e) => setPassword(e.target.value)}
              placeholder="输入密码"
              required
            />
          </div>
          <button type="submit" className="auth-button" disabled={loading}>
            {loading ? '登录中...' : '登录'}
          </button>
        </form>
        <p className="auth-switch">
          没有账号?{' '}
          <button onClick={onSwitchToRegister} className="link-button">
            立即注册
          </button>
        </p>
      </div>
    </div>
  );
}
