// frontend/src/pages/Login.tsx
import { createSignal, Show } from 'solid-js';
import { useNavigate, A } from '@solidjs/router';
import authStore from '../store/authStore';
import { cn } from '../utils/cn';

export default function Login() {
  const [username, setUsername] = createSignal('');
  const [password, setPassword] = createSignal('');
  const [error, setError] = createSignal('');
  const [loading, setLoading] = createSignal(false);

  const { login } = authStore;
  const navigate = useNavigate();

  const handleSubmit = async (e: Event) => {
    e.preventDefault();
    setError('');
    setLoading(true);

    try {
      await login(username(), password());
      navigate('/');
    } catch (err: any) {
      setError(err.message || '登录失败');
    } finally {
      setLoading(false);
    }
  };

  return (
    <div class="min-h-screen bg-gradient-to-br from-slate-900 via-purple-900 to-slate-900 flex items-center justify-center p-4">
      <div class="w-full max-w-md">
        <div class="bg-slate-800/50 backdrop-blur-xl rounded-2xl shadow-2xl p-8 border border-slate-700/50">
          <div class="text-center mb-8">
            <h1 class="text-3xl font-bold text-white mb-2">可视化大屏系统</h1>
            <p class="text-slate-400">登录您的账户</p>
          </div>

          <form onSubmit={handleSubmit} class="space-y-6">
            <div>
              <label class="block text-sm font-medium text-slate-300 mb-2">
                用户名
              </label>
              <input
                type="text"
                value={username()}
                onInput={(e) => setUsername(e.target.value)}
                class={cn(
                  'w-full px-4 py-3 bg-slate-700/50 border border-slate-600 rounded-lg',
                  'text-white placeholder-slate-400 focus:outline-none focus:ring-2 focus:ring-purple-500 focus:border-transparent',
                  'transition-all duration-200'
                )}
                placeholder="请输入用户名"
                required
              />
            </div>

            <div>
              <label class="block text-sm font-medium text-slate-300 mb-2">
                密码
              </label>
              <input
                type="password"
                value={password()}
                onInput={(e) => setPassword(e.target.value)}
                class={cn(
                  'w-full px-4 py-3 bg-slate-700/50 border border-slate-600 rounded-lg',
                  'text-white placeholder-slate-400 focus:outline-none focus:ring-2 focus:ring-purple-500 focus:border-transparent',
                  'transition-all duration-200'
                )}
                placeholder="请输入密码"
                required
              />
            </div>

            <Show when={error()}>
              <div class="bg-red-500/20 border border-red-500/50 text-red-400 px-4 py-3 rounded-lg text-sm">
                {error()}
              </div>
            </Show>

            <button
              type="submit"
              disabled={loading()}
              class={cn(
                'w-full py-3 px-4 bg-gradient-to-r from-purple-600 to-blue-600 text-white font-semibold rounded-lg',
                'hover:from-purple-700 hover:to-blue-700 focus:outline-none focus:ring-2 focus:ring-purple-500 focus:ring-offset-2 focus:ring-offset-slate-800',
                'transition-all duration-200 transform hover:scale-[1.02]',
                'disabled:opacity-50 disabled:cursor-not-allowed disabled:transform-none'
              )}
            >
              {loading() ? '登录中...' : '登录'}
            </button>
          </form>

          <div class="mt-6 text-center">
            <p class="text-slate-400">
              还没有账户？{' '}
              <A href="/register" class="text-purple-400 hover:text-purple-300 font-medium transition-colors">
                立即注册
              </A>
            </p>
          </div>
        </div>
      </div>
    </div>
  );
}

// src/pages/Login.tsx
import React, { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { Lock, User, Eye, EyeOff } from 'lucide-react';
import { useAuth } from '@/context/AuthContext';
import Button from '@/components/ui/Button';
import { Card } from '@/components/ui/Card';

const Login: React.FC = () => {
  const [username, setUsername] = useState('');
  const [password, setPassword] = useState('');
  const [showPassword, setShowPassword] = useState(false);
  const [error, setError] = useState('');
  const [loading, setLoading] = useState(false);
  
  const { login, currentUser } = useAuth();
  const navigate = useNavigate();

  if (currentUser) {
    navigate('/');
    return null;
  }

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setError('');
    setLoading(true);

    await new Promise(resolve => setTimeout(resolve, 500));

    if (!username || !password) {
      setError('请输入用户名和密码');
      setLoading(false);
      return;
    }

    const success = login(username, password);
    if (success) {
      navigate('/');
    } else {
      setError('用户名或密码错误');
    }
    setLoading(false);
  };

  return (
    <div className="min-h-screen bg-gradient-to-br from-primary-dark via-primary to-primary-light flex items-center justify-center p-4">
      <div className="absolute inset-0 overflow-hidden">
        <div className="absolute -top-40 -right-40 w-80 h-80 bg-blue-400 rounded-full opacity-20 blur-3xl"></div>
        <div className="absolute -bottom-40 -left-40 w-80 h-80 bg-blue-300 rounded-full opacity-20 blur-3xl"></div>
      </div>

      <Card className="w-full max-w-md relative z-10" padding={false}>
        <div className="p-8">
          <div className="text-center mb-8">
            <div className="w-16 h-16 bg-primary rounded-xl flex items-center justify-center mx-auto mb-4">
              <span className="text-white font-bold text-2xl">H</span>
            </div>
            <h1 className="text-2xl font-bold text-gray-900">酒店管理系统</h1>
            <p className="text-gray-500 mt-2">请登录您的账号</p>
          </div>

          <form onSubmit={handleSubmit} className="space-y-6">
            <div className="space-y-1">
              <label className="block text-sm font-medium text-gray-700">用户名</label>
              <div className="relative">
                <User className="absolute left-3 top-1/2 -translate-y-1/2 w-5 h-5 text-gray-400" />
                <input
                  type="text"
                  value={username}
                  onChange={(e) => setUsername(e.target.value)}
                  placeholder="请输入用户名"
                  className="w-full pl-10 pr-4 py-2.5 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-primary-light focus:border-primary transition-colors"
                />
              </div>
            </div>

            <div className="space-y-1">
              <label className="block text-sm font-medium text-gray-700">密码</label>
              <div className="relative">
                <Lock className="absolute left-3 top-1/2 -translate-y-1/2 w-5 h-5 text-gray-400" />
                <input
                  type={showPassword ? 'text' : 'password'}
                  value={password}
                  onChange={(e) => setPassword(e.target.value)}
                  placeholder="请输入密码"
                  className="w-full pl-10 pr-12 py-2.5 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-primary-light focus:border-primary transition-colors"
                />
                <button
                  type="button"
                  onClick={() => setShowPassword(!showPassword)}
                  className="absolute right-3 top-1/2 -translate-y-1/2 text-gray-400 hover:text-gray-600"
                >
                  {showPassword ? <EyeOff className="w-5 h-5" /> : <Eye className="w-5 h-5" />}
                </button>
              </div>
            </div>

            {error && (
              <div className="p-3 bg-red-50 border border-red-200 rounded-lg">
                <p className="text-sm text-red-600">{error}</p>
              </div>
            )}

            <Button type="submit" className="w-full" size="lg" loading={loading}>
              登录
            </Button>
          </form>

          <div className="mt-6 pt-6 border-t border-gray-100">
            <p className="text-sm text-gray-500 text-center mb-3">测试账号</p>
            <div className="grid grid-cols-2 gap-2 text-xs">
              <div className="p-2 bg-gray-50 rounded-lg">
                <p className="font-medium text-gray-700">管理员</p>
                <p className="text-gray-500">admin / admin123</p>
              </div>
              <div className="p-2 bg-gray-50 rounded-lg">
                <p className="font-medium text-gray-700">经理</p>
                <p className="text-gray-500">manager / manager123</p>
              </div>
              <div className="p-2 bg-gray-50 rounded-lg">
                <p className="font-medium text-gray-700">前台</p>
                <p className="text-gray-500">reception1 / reception123</p>
              </div>
              <div className="p-2 bg-gray-50 rounded-lg">
                <p className="font-medium text-gray-700">客房</p>
                <p className="text-gray-500">housekeeping1 / hk123</p>
              </div>
            </div>
          </div>
        </div>
      </Card>
    </div>
  );
};

export default Login;
